### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by andymarden** [mnaoumov/obsidian-refresh-preview#1]
Do you think there is a way you add auto refresh? This could have number of seconds in Options and do a reload in the background after that amount of time if the file has changed. Maybe a file watcher could be used if secs is zero so it triggers on the event rather than polls 

Use case - shared vault - someone else updates the note I am looking at - syncthing then rejects the file change within a few secs - my note preview refreshes.

**Comment by andymarden** [comment]
Don't mind doing a pull request and having a go myself if you can give me some thoughts/pointers

**Comment by mnaoumov** [comment]
Added in https://github.com/mnaoumov/obsidian-refresh-preview/releases/tag/2.0.0
